import turtle as tr       
tr.shape('turtle')     
tr.shape('turtle')    
tr.color('black')     
tr.up()               
tr.goto (100, 0)      
tr.left(90)           
tr.down()             
tr.fillcolor('yellow')
tr.begin_fill()       
tr.circle(100)        
tr.end_fill()         
tr.up()               
tr.goto(-30, 50)      
tr.down()             
tr.fillcolor('blue')  
tr.begin_fill()       
tr.circle(15)         
tr.end_fill()         
tr.up()               
tr.goto(60, 50)       
tr.down()             
tr.fillcolor('blue')  
tr.begin_fill()       
tr.circle(15)         
tr.end_fill()         
tr.up()               
tr.goto(0, 30)        
tr.down()             
tr.color('black')     
tr.pensize(8)         
tr.left(180)          
tr.forward(50)        
tr.up()               
tr.goto(70, -10)      
tr.color('red')       
tr.down()             
tr.circle(-70, 180, 30)   
